### Objective Of Week 1 Assignment :-

Learn Python basics and perform basic data exploration and cleaning using Pandas. Steps:

1- Load a CSV dataset into a Pandas DataFrame.

2- Explore data (head/tail, shape, columns, data types).

3- Handle missing values (identify, fill/drop).

4- Perform basic operations (filter rows, select columns).

5- Remove duplicates.

6- Create a derived column (total_amount = price * quantity).

7- Save the cleaned dataset as a new CSV file.

Output: Jupyter Notebook (.ipynb) + cleaned CSV + brief summary.

------------------------------

## 1.We are loading the CSV dataset into a Pandas DataFrame for data analysis and preprocessing.

In [3]:
import pandas as pd
import numpy as np

In [6]:
ecom_data = pd.read_csv("DataSet/e-commerce-dataset.csv")
ecom_data

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

--------------------------------

## 2.Now, we are going to explore the dataset by examining its head and tail records, shape, column names, sample, and data types

In [7]:
ecom_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [8]:
ecom_data.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [9]:
ecom_data.head(1)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [10]:
ecom_data.tail(1)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [12]:
ecom_data.sample()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
201,20195790,Dupatta Bazaar,Sequin Embroidered Net Dupatta,4.7,10,999,48.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/201...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",dupatta

In [13]:
ecom_data.sample(2)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
337,22217088,DressBerry,Open Back Flatform Heels,4.1,34,1599,54.0,"""₹735.00""",INR,http://assets.myntassets.com/assets/images/222...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",KIR███ENT███RIS███,"[{""size"":""36"",""value"":""23.2cm"",""value_name"":""T...",NaN,LOW███GRO███ FL█████████ERT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",heels
641,20042696,Flying Machine,Men White Standard Slim Fit Solid Casual Shirt,3.9,102,1999,55.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":16,""2_stars"":5,""3_stars"":8,""4_stars""...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""36"",""value"":""36.0in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts

In [14]:
ecom_data.shape

(1000, 24)

In [15]:
ecom_data.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [17]:
ecom_data.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

-----------------

## 3.Now, we are going to handle missing values by identifying them and applying appropriate techniques such as filling or dropping the missing data.

In [18]:
ecom_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [19]:
ecom_data.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [21]:
ecom_data[['discount','what_customers_said',]]

     discount what_customers_said
0        58.0                 NaN
1        35.0                 NaN
2        65.0                 NaN
3        52.0                 NaN
4        17.0                 NaN
..        ...                 ...
995      50.0                 NaN
996      45.0                 NaN
997      50.0                 NaN
998      20.0                 NaN
999      31.0                 NaN

[1000 rows x 2 columns]

In [22]:
ecom_data['seller_name'].fillna('Unknown Seller Name',inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9760\696256919.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['seller_name'].fillna('Unknown Seller Name',inplace=True)

In [25]:
ecom_data['what_customers_said'].fillna('No reviews from customer',inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9760\2702441426.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['what_customers_said'].fillna('No reviews from customer',inplace=True)

In [26]:
ecom_data['videos'].fillna('No Url',inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9760\2410088154.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['videos'].fillna('No Url',inplace=True)

In [28]:
ecom_data['variations'].fillna('[]',inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9760\870936592.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['variations'].fillna('[]',inplace=True)

In [29]:
ecom_data['seller_information'].fillna('[]',inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9760\3830924156.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['seller_information'].fillna('[]',inplace=True)

In [32]:
ecom_data['discount'].fillna(0,inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_9760\1779432581.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['discount'].fillna(0,inplace=True)

In [33]:
ecom_data.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

---------------------------------------------

## 4.Now, we are going to perform basic data operations such as filtering rows and selecting specific columns from the dataset.

In [35]:
ecom_data[ecom_data['rating']>3.9]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No reviews from customer,Unknown Seller Name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Url,[],"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No reviews from customer,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No Url,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews from customer,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews from customer,Br ███erp███es,"[{""size"":""Onesize""}]",No Url,Kha███ no███122█████████lhi██████████████████,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No reviews from customer,Tru███m R███il,"[{""size"":""Onesize""}]",No Url,Sho███o. ███-10█████████enu███████████████████...,[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [40]:
ecom_data[(ecom_data['rating']>=4.3) & (ecom_data['ratings_count']>=200)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No reviews from customer,Unknown Seller Name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
24,15115018,Jockey,Non-Wired Non-Padded Combed Cotton Workout Bra...,4.4,1582,579,0.0,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":90,""2_stars"":25,""3_stars"":93,""4_star...",No reviews from customer,Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Ov...",No Url,Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
107,18962984,Athena,Burgundy Off-Shoulder Scrunchie Bodycon Dress,4.3,236,2499,68.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":23,""2_stars"":5,""3_stars"":15,""4_stars...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",APE███PPA███S,"[{""size"":""XS"",""value"":""8.0in"",""value_name"":""Sl...",No Url,"Plo███o. ███, P█████████2Se███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
143,10691426,SASSAFRAS,Black & Beige Ikat Print Cotton Shirt Dress,4.5,4441,2199,65.0,"""₹769.00""",INR,http://assets.myntassets.com/assets/images/106...,...,"{""1_star"":126,""2_stars"":78,""3_stars"":288,""4_st...","[{""percentage"":""79"",""value_name"":""Fit, Just Ri...",ARD███ Re███l C███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No Url,Khe███ No███76/█████████il ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
209,10564232,PRITA BY PRIYAASI,Multicoloured Gold-Plated Beaded Handcrafted C...,4.3,727,1130,69.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/105...,...,"{""1_star"":48,""2_stars"":26,""3_stars"":62,""4_star...",No reviews from customer,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]","[""rw-10564232_cae700""]",PRI███DES███S P█████████MIT███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
211,10135431,Priyaasi,Green Gold-Plated Dome Shaped Jhumkas,4.5,347,1000,50.0,"""₹500.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":12,""2_stars"":5,""3_stars"":18,""4_stars...",No reviews from customer,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]","[""rw-10135431_cae700""]",PRI███DES███S P█████████MIT███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
258,15787112,Mamaearth,Oil-Free Face Moisturizer With Turmeric & Saff...,4.3,903,319,12.0,"""₹280.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":40,""2_stars"":23,""3_stars"":77,""4_star...",No reviews from customer,Hon███ Co███mer█████████Lim██████,"[{""size"":""75-100 ML""}]",No Url,Plo███o 6███4th█████████LM ███████████████████...,[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",face-moisturisers
347,19020502,U.S. Polo Assn.,Men Red & Navy Blue Colourblocked Puffer Jacket,4.4,338,6299,53.0,"""₹2,960.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":17,""2_stars"":7,""3_stars"":14,""4_stars...","[{""percentage"":""71"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Url,10T███LOO███DU █████████ITY███████████████████...,[],"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
383,18973888,Levis,Men Skinny Fit Heavy Fade Stretchable Jeans,4.4,333,4099,0.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":26,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""74"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973888_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,[],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
398,18973728,Levis,Men 65504 Skinny Tapered Fit Jeans,4.4,260,4399,47.0,"""₹4,399.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":18,""2_stars"":6,""3_stars"":13,""4_stars...","[{""percentage"":""82"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973728_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,[],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
399,18903330,Levis,Women Blue Skinny Fit High-Rise Stretchable Jeans,4.4,235,3299,20.0,"""₹1,649.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":13,""2_stars"":4,""3_stars"":16,""4_stars...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""25"",""value"":""25.0in"",""value_name"":""T...","[""rw-18903330_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
400,18973740,Levis,Men Blue 512 Slim Tapered Fit Mid Rise Stretch...,4.3,340,4099,57.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":28,""2_stars"":12,""3_stars"":14,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973740_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,[],"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
430,18973914,Levis,Men Blue 512 Slim Tapered Fit Mid Rise Light F...,4.4,243,3799,60.0,"""₹2,089.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":15,""2_stars"":5,""3_stars"":12,""4_stars...","[{""percentage"":""81"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973914_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
473,13446422,Biba,Women Cream-Coloured Motifs Print Panelled Cot...,4.4,749,4995,50.0,"""₹2,997.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":44,""2_stars"":17,""3_stars"":56,""4_star...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",Fla███tar███mme██████,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""To...","[""rw-13446422_cae700""]","1st███oor███abi█████████02,███████████████████...",[],"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",kurta-sets
653,13624708,Nike,Men Black Solid Standard Fit CHALLENGER DRI FI...,4.4,376,1795,0.0,"""₹1,795.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":22,""2_stars"":8,""3_stars"":22,""4_stars...",No reviews from customer,Unknown Seller Name,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shorts
719,18373646,ADIDAS,Men Black Woven Design Immute Running Shoes,4.3,319,3799,35.0,"""₹2,469.00""",INR,http://assets.myntassets.com/assets/images/183...,...,"{""1_star"":21,""2_stars"":5,""3_stars"":25,""4_stars...",No reviews from customer,Fla███tar███mme██████,"[{""size"":""6"",""value"":""24.5cm"",""value_name"":""To...","[""rw-18373646_cae700"",""https://videos.myntasse...","1st███oor███abi█████████02,███████████████████...",[],"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",sports-shoes
746,11990978,Roadster,Women Red & Grey Melange Abstract Self Design ...,4.4,302,1999,61.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":10,""2_stars"":12,""3_stars"":18,""4_star...","[{""percentage"":""82"",""value_name"":""Fit, Just Ri...",Unknown Seller Name,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweaters
748,11990952,Roadster,Women Red Ribbed Pullover Sweater,4.3,449,1699,61.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":33,""2_stars"":11,""3_stars"":33,""4_star...","[{""percentage"":""66"",""value_name"":""Fit, Just Ri...",Unknown Seller Name,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""B...",No Url,[],"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweaters
773,6510138,Roadster,Men Black Solid Hooded Sweatshirt,4.3,959,1999,50.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/651...,...,"{""1_star"":49,""2_stars"":29,""3_stars"":68,""4_star...","[{""percentage"":""84"",""value_name"":""Fit, Just Ri...",Unknown Seller Name,"[{""size"":""S"",""value"":""40.5in"",""value_name"":""Ch...","[""rw-6510138_cae700""]",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
839,17268524,H&M,Women Brown Halter Neck Cropped Top,4.4,203,699,25.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":6,""2_stars"":8,""3_stars"":12,""4_stars""...",No reviews from customer,Unknown Seller Name,"[{""size"":""XXS"",""value"":""30.0in"",""value_name"":""...",No Url,[],"[{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
950,13502414,Puma,Men Navy Blue & White Performance Cat Printed ...,4.3,327,1499,0.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":22,""2_stars"":11,""3_stars"":22,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",Unknown Seller Name,"[{""size"":""XS"",""value"":""36.61in"",""value_name"":""...","[""rw-13502414_cae700""]",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
966,12953958,Allen Solly,Men Maroon Solid Polo Collar Pure Cotton T-shirt,4.4,409,999,40.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"{""1_star"":17,""2_stars"":6,""3_stars"":26,""4_stars...","[{""percentage"":""96"",""value_name"":""Fit, Just Ri...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-12953958_cae700"",""https://videos.myntasse...","Gro███ Fl███, N█████████old███████████████████...",[],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
972,16287616,Juniper,Lime Green Mandarin Collar Printed Tunic,4.3,346,1299,51.0,"""₹636.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":16,""2_stars"":14,""3_stars"":35,""4_star...",No reviews from customer,AMA███XPO███ IN█████████AL █████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No Url,G-9███SIT███RA █████████L A███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
973,16287462,Juniper,Yellow Mandarin Collar Printed Tunic,4.3,335,1299,43.0,"""₹740.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":16,""2_stars"":13,""3_stars"":29,""4_star...",No reviews from customer,AMA███XPO███ IN█████████AL,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No Url,G-9███PIP███ICO█████████AL ███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
975,16293018,Nayo,Black & White Printed Cotton Kurti,4.3,687,1199,43.0,"""₹683.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":32,""2_stars"":28,""3_stars"":51,""4_star...",No reviews from customer,Bhu███E R███il █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",No Url,"F-███-A,███t, █████████flo███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
979,9452773,Louis Philippe,Men Brown Solid Leather Two Fold Wallet,4.3,401,1799,25.0,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/945...,...,"{""1_star"":23,""2_stars"":5,""3_stars"":21,""4_stars...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
988,8076639,French Connection,Women Charcoal Grey Analogue Watch FC1317RGM,4.4,563,6250,60.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/807...,...,"{""1_star"":35,""2_stars"":21,""3_stars"":22,""4_star...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-8076639_cae700"",""https://videos.myntasset...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",No reviews from customer,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [41]:
ecom_data[(ecom_data['rating']>=4.3) & (ecom_data['ratings_count']>=200)].shape

(29, 24)

In [37]:
ecom_data[ecom_data['discount']>=50]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No reviews from customer,Unknown Seller Name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]",No Url,[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",No Url,[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",No reviews from customer,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",No reviews from customer,Br ███erp███es,"[{""size"":""Onesize""}]",No Url,Kha███ no███122█████████lhi██████████████████,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""pi-13698258""]",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]",No Url,[],"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [47]:
ecom_data[['product_id', 'title', 'category', 'rating', 'ratings_count']]

     product_id           title   category  rating  ratings_count
0       8376765     Lino Perros  backpacks     3.8             15
1       9136281  Tommy Hilfiger  backpacks     4.5             67
2      17633752           Lavie  backpacks     4.4            226
3       1376949          F Gear  backpacks     4.4           1052
4      13939916       MYTRIDENT  bath-robe     4.7             12
..          ...             ...        ...     ...            ...
995    13698258           KREDO    watches     3.5             11
996    16896006           GUESS    watches     5.0             22
997     1708108        GIORDANO    watches     2.8              5
998    19280114        Fastrack    watches     4.3             17
999    18601682         BOLDFIT  yoga-mats     3.8            161

[1000 rows x 5 columns]

In [44]:
ecom_data[['product_id', 'title', 'seller_name', 'seller_information']]

,product_id,title,seller_name,seller_information
0,8376765,Lino Perros,Unknown Seller Name,[]
1,9136281,Tommy Hilfiger,Unknown Seller Name,[]
2,17633752,Lavie,Unknown Seller Name,[]
3,1376949,F Gear,Unknown Seller Name,[]
4,13939916,MYTRIDENT,Unknown Seller Name,[]
...,...,...,...,...
995,13698258,KREDO,Unknown Seller Name,[]
996,16896006,GUESS,Unknown Seller Name,[]
997,1708108,GIORDANO,Unknown Seller Name,[]
998,19280114,Fastrack,Tru███m R███il,Sho███o. ███-10█████████enu███████████████████...
999,18601682,BOLDFIT,Unknown Seller Name,[]

In [45]:
ecom_data[['product_id', 'title','best_offer', 'more_offers']]

,product_id,title,best_offer,more_offers
0,8376765,Lino Perros,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
1,9136281,Tommy Hilfiger,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
2,17633752,Lavie,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
3,1376949,F Gear,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
4,13939916,MYTRIDENT,{},"[{""offer_name"":""10% Instant Discount on IndusI..."
...,...,...,...,...
995,13698258,KREDO,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
996,16896006,GUESS,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
997,1708108,GIORDANO,{},"[{""offer_name"":""10% Instant Discount on Citi C..."
998,19280114,Fastrack,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI..."
999,18601682,BOLDFIT,{},"[{""offer_name"":""10% Instant Discount on Citi C..."

----------------------------

## 5.Now, we are going to identify and remove duplicate records from the dataset.

In [48]:
ecom_data.duplicated().sum()

np.int64(0)

#### No duplicate data was found in the dataset.

------------------------------

## 6.Now, we are going to create a derived column, total_amount, by multiplying the price and quantity columns.

In [49]:
ecom_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No reviews from customer,Unknown Seller Name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No reviews from customer,Unknown Seller Name,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Url,[],"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [51]:
ecom_data['final_price'] = ecom_data['final_price'].str.replace('[₹]','',regex=True)

In [52]:
ecom_data['final_price'] = ecom_data['final_price'].str.replace('[,]','',regex=True)

In [53]:
ecom_data['final_price'] = ecom_data['final_price'].str.replace('["]','',regex=True)

In [56]:
ecom_data['final_price'] = ecom_data['final_price'].astype(float)

In [57]:
ecom_data['final_price']

0       3995.0
1       2899.0
2       2999.0
3       1675.0
4       2899.0
        ...
995    11890.0
996     8900.0
997     7950.0
998     2636.0
999      699.0
Name: final_price, Length: 1000, dtype: float64

In [58]:
ecom_data.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price               float64
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [60]:
ecom_data['total_amount'] = ecom_data['ratings_count'] * ecom_data['final_price']

In [61]:
ecom_data.sample()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
496,17307424,Clora Creation,Women Set of 2 Multi Palazzos,4.0,3,2399,59.0,983.0,INR,http://assets.myntassets.com/assets/images/173...,...,No reviews from customer,Clo███Cre███on,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Url,C-1███ Ba███ent█████████Col███████████████████...,[],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",palazzos,2949.0

In [62]:
ecom_data

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",[],[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",[],"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",[],"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,677774.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1762100.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Url,[],"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,34788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""pi-13698258""]",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,130790.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",[],[],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,195800.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Onesize""}]",No Url,[],"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,39750.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,No reviews from customer,Tru███m R███il,"[{""size"":""Onesize""}]",No Url,Sho███o. ███-10█████████enu███████████████████...,[],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,44812.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,No reviews from customer,Unknown Seller Name,"[{""size"":""Medium""}]",No Url,[],"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,112539.0

-------------------------------------------

## 7.Finally, we are going to save the cleaned dataset as a new CSV file for further analysis and future use.

In [65]:
ecom_data.to_csv('e-commerce-dataset-Final.csv', index=False)
print("CSV file saved successfully.")

CSV file saved successfully.