In [13]:
import pandas as pd

## Cleaning orders.csv

In [14]:
df = pd.read_csv("orders.csv")

In [15]:
df.head()

   order_id  customer_id           order_date     status region_code
0         1         63.0  2025-04-17 04:10:45    SHIPPED       NORTH
1         2        108.0  2024-11-25 06:42:20     PLACED       SOUTH
2         3        353.0  2026-05-01 16:44:50     PLACED        WEST
3         4        130.0  2024-09-28 20:29:28  DELIVERED        EAST
4         5          NaN  2025-12-03 04:47:00  CANCELLED        WEST

#### Fix Date Formats

In [16]:
df["order_date"] = pd.to_datetime(df["order_date"],format="mixed",dayfirst=True)

In [17]:
df.head()

   order_id  customer_id          order_date     status region_code
0         1         63.0 2025-04-17 04:10:45    SHIPPED       NORTH
1         2        108.0 2024-11-25 06:42:20     PLACED       SOUTH
2         3        353.0 2026-05-01 16:44:50     PLACED        WEST
3         4        130.0 2024-09-28 20:29:28  DELIVERED        EAST
4         5          NaN 2025-12-03 04:47:00  CANCELLED        WEST

#### Handle Missing Customer IDs and Correct datatype

In [18]:
df["customer_id"] = df["customer_id"].fillna(0)
df["customer_id"] = df["customer_id"].astype("Int64")

In [19]:
df

     order_id  customer_id          order_date     status region_code
0           1           63 2025-04-17 04:10:45    SHIPPED       NORTH
1           2          108 2024-11-25 06:42:20     PLACED       SOUTH
2           3          353 2026-05-01 16:44:50     PLACED        WEST
3           4          130 2024-09-28 20:29:28  DELIVERED        EAST
4           5            0 2025-12-03 04:47:00  CANCELLED        WEST
..        ...          ...                 ...        ...         ...
495       496          234 2025-10-17 15:21:09    SHIPPED        WEST
496       497           59 2024-07-28 21:46:39     PLACED       SOUTH
497       498          212 2024-12-11 16:18:09  CANCELLED        WEST
498       499          167 2024-12-30 09:44:12    SHIPPED        EAST
499       500          363 2024-10-10 15:06:17     PLACED        WEST

[500 rows x 5 columns]

In [20]:
df.to_csv("clean_orders.csv",index=False)

------------------

## Cleaning products.csv

In [21]:
df = pd.read_csv("products.csv")

In [22]:
df.head(10)

   product_id  product_name     category subcategory  cost_price
0           1    Headphones  Electronics  Headphones        1251
1           2        Laptop  Electronics      Laptop         612
2           3    Headphones  Electronics  Headphones        3756
3           4         Mouse  Electronics       Mouse        1768
4           5    KEYBOARD    Electronics    Keyboard        2329
5           6        Mobile  Electronics      Mobile        3217
6           7    Headphones  Electronics  Headphones         157
7           8      Keyboard  Electronics    Keyboard         295
8           9      LAPTOP    Electronics      Laptop        4577
9          10        Laptop  Electronics      Laptop         747

#### Remove Extra Spaces

In [23]:
df["product_name"] = df["product_name"].str.strip()

In [24]:
df.head(10)

   product_id product_name     category subcategory  cost_price
0           1   Headphones  Electronics  Headphones        1251
1           2       Laptop  Electronics      Laptop         612
2           3   Headphones  Electronics  Headphones        3756
3           4        Mouse  Electronics       Mouse        1768
4           5     KEYBOARD  Electronics    Keyboard        2329
5           6       Mobile  Electronics      Mobile        3217
6           7   Headphones  Electronics  Headphones         157
7           8     Keyboard  Electronics    Keyboard         295
8           9       LAPTOP  Electronics      Laptop        4577
9          10       Laptop  Electronics      Laptop         747

#### Convert to Title Case

In [25]:
df["product_name"] = df["product_name"].str.title()

In [26]:
df.head(10)

   product_id product_name     category subcategory  cost_price
0           1   Headphones  Electronics  Headphones        1251
1           2       Laptop  Electronics      Laptop         612
2           3   Headphones  Electronics  Headphones        3756
3           4        Mouse  Electronics       Mouse        1768
4           5     Keyboard  Electronics    Keyboard        2329
5           6       Mobile  Electronics      Mobile        3217
6           7   Headphones  Electronics  Headphones         157
7           8     Keyboard  Electronics    Keyboard         295
8           9       Laptop  Electronics      Laptop        4577
9          10       Laptop  Electronics      Laptop         747

In [27]:
df.to_csv("clean_products.csv",index=False)

---------------------------

## validate emails

In [28]:
df = pd.read_csv("customers.csv")
df.head()

,customer_id,customer_name,email,registration_date,customer_type
0,1,Micheal Larsen,christina78@example.com,2025-12-29,VIP
1,2,Jeffrey Phillips,michelle68@example.net,2026-05-01,VIP
2,3,Latoya Perry,patricia61@example.com,2026-06-08,REGULAR
3,4,Bethany Santana,wanda38@example.com,2026-02-20,VIP
4,5,Ashley Harper,dianafischer@example.org,2024-01-12,PREMIUM

In [29]:
email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
is_valid = df["email"].astype(str).str.match(email_pattern)

In [30]:
bad_customer_ids = df.loc[~is_valid, "customer_id"].tolist()
 
df["email_valid"] = is_valid
df.to_csv("customers_clean.csv", index=False)

---------------------

## check referential integrity

In [31]:
orders = pd.read_csv("orders.csv")
items = pd.read_csv("order_items.csv")

In [32]:
valid_order_ids = set(orders["order_id"])
orphan_mask = ~items["order_id"].isin(valid_order_ids)
orphans = items[orphan_mask]

items.to_csv("clean_order_items.csv", index=False)

---------------